#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef SHUFTIPRO_SWIFT_H
#define SHUFTIPRO_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import CoreGraphics;
@import CoreMedia;
@import Foundation;
@import MessageUI;
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ShuftiPro",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class UIColor;
@class NSCoder;

/// Computed properties, based on the backing CALayer property, that are visible in Interface Builder.
IB_DESIGNABLE
SWIFT_CLASS("_TtC9ShuftiPro12ANCustomView")
@interface ANCustomView : UIView
/// When positive, the background of the layer will be drawn with rounded corners. Also effects the mask generated by the `masksToBounds’ property. Defaults to zero. Animatable.
@property (nonatomic) IBInspectable double cornerRadius;
/// The width of the layer’s border, inset from the layer bounds. The border is composited above the layer’s content and sublayers and includes the effects of the `cornerRadius’ property. Defaults to zero. Animatable.
@property (nonatomic) IBInspectable double borderWidth;
/// The color of the layer’s border. Defaults to opaque black. Colors created from tiled patterns are supported. Animatable.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
/// The color of the shadow. Defaults to opaque black. Colors created from patterns are currently NOT supported. Animatable.
@property (nonatomic, strong) IBInspectable UIColor * _Nullable shadowColor;
/// The opacity of the shadow. Defaults to 0. Specifying a value outside the [0,1] range will give undefined results. Animatable.
@property (nonatomic) IBInspectable float shadowOpacity;
/// The shadow offset. Defaults to (0, -3). Animatable.
@property (nonatomic) IBInspectable CGSize shadowOffset;
/// The blur radius used to create the shadow. Defaults to 3. Animatable.
@property (nonatomic) IBInspectable double shadowRadius;
@property (nonatomic) IBInspectable CGFloat leftTopRadius;
@property (nonatomic) IBInspectable CGFloat rightTopRadius;
@property (nonatomic) IBInspectable CGFloat rightBottomRadius;
@property (nonatomic) IBInspectable CGFloat leftBottomRadius;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UITouch;
@class UIEvent;

/// Lottie comes prepacked with a two Animated Controls, <code>AnimatedSwitch</code> and
/// <code>AnimatedButton</code>. Both of these controls are built on top of <code>AnimatedControl</code>
/// <code>AnimatedControl</code> is a subclass of <code>UIControl</code> that provides an interactive
/// mechanism for controlling the visual state of an animation in response to
/// user actions.
/// The <code>AnimatedControl</code> will show and hide layers depending on the current
/// <code>UIControl.State</code> of the control.
/// Users of <code>AnimationControl</code> can set a Layer Name for each <code>UIControl.State</code>.
/// When the state is change the <code>AnimationControl</code> will change the visibility
/// of its layers.
/// NOTE: Do not initialize directly. This is intended to be subclassed.
SWIFT_CLASS("_TtC9ShuftiPro15AnimatedControl")
@interface AnimatedControl : UIControl
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, getter=isEnabled) BOOL enabled;
@property (nonatomic, getter=isSelected) BOOL selected;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (BOOL)beginTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (BOOL)continueTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (void)endTrackingWithTouch:(UITouch * _Nullable)touch withEvent:(UIEvent * _Nullable)event;
- (void)cancelTrackingWithEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


/// An interactive button that plays an animation when pressed.
SWIFT_CLASS("_TtC9ShuftiPro14AnimatedButton")
@interface AnimatedButton : AnimatedControl
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (BOOL)beginTrackingWithTouch:(UITouch * _Nonnull)touch withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
- (void)endTrackingWithTouch:(UITouch * _Nullable)touch withEvent:(UIEvent * _Nullable)event;
@property (nonatomic) UIAccessibilityTraits accessibilityTraits;
@end



/// An interactive switch with an ‘On’ and ‘Off’ state. When the user taps on the
/// switch the state is toggled and the appropriate animation is played.
/// Both the ‘On’ and ‘Off’ have an animation play range associated with their state.
SWIFT_CLASS("_TtC9ShuftiPro14AnimatedSwitch")
@interface AnimatedSwitch : AnimatedControl
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)endTrackingWithTouch:(UITouch * _Nullable)touch withEvent:(UIEvent * _Nullable)event;
@property (nonatomic) UIAccessibilityTraits accessibilityTraits;
@end

@class CAAnimation;

SWIFT_CLASS("_TtC9ShuftiPro27AnimationCompletionDelegate")
@interface AnimationCompletionDelegate : NSObject <CAAnimationDelegate>
- (void)animationDidStop:(CAAnimation * _Nonnull)anim finished:(BOOL)flag;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A view that can be added to a keypath of an AnimationView
SWIFT_CLASS("_TtC9ShuftiPro16AnimationSubview")
@interface AnimationSubview : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A base <code>CALayer</code> that manages the frame and animations
/// of its <code>sublayers</code> and <code>mask</code>
SWIFT_CLASS("_TtC9ShuftiPro18BaseAnimationLayer")
@interface BaseAnimationLayer : CALayer
- (void)layoutSublayers;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The base type of <code>AnimationLayer</code> that can contain other <code>AnimationLayer</code>s
SWIFT_CLASS("_TtC9ShuftiPro20BaseCompositionLayer")
@interface BaseCompositionLayer : BaseAnimationLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (void)addSublayer:(CALayer * _Nonnull)layer;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end
























SWIFT_CLASS("_TtC9ShuftiPro7CallApi")
@interface CallApi : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;
@class UILabel;
@class WKWebView;
@class UIButton;
@class LoadingButton;
@class UIScrollView;
@class RAProgressRing;
@class UISwipeGestureRecognizer;
@class NSString;
@class NSBundle;

SWIFT_CLASS("_TtC9ShuftiPro9CameraVc2")
@interface CameraVc2 : UIViewController <AVCaptureFileOutputRecordingDelegate>
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified document_frame;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified errorView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified errorImageView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified flipCardImageView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified guideLblView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified bottomView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified captureFrontSideLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified recordingLbl;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified flipCardLoader;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified instructionsImg;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified previewView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified flashImg;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified flashBtn;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified recordButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified captureGuideLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified captureGuideTopLbl;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified switchCameraBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified uploadPassportButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified backBtnImg;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified countDownLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified supportedTypesLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified countDownView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified innerCameraView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified instructionSubView1;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified instructionSubView2;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified instructionSubView3;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified instructionSubView4;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified instructionSubView5;
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified instructionScrollView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified cancelImage;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cancelBtn;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified verificationType;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified retryAutoCaptureBtn;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified timerCounter;
@property (nonatomic, weak) IBOutlet RAProgressRing * _Null_unspecified counterView;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)applicationWillEnterForeground;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (IBAction)uploadPassportBtnPressedWithSender:(UIButton * _Nonnull)sender;
- (IBAction)backBtnPressedOnCamera:(id _Nonnull)sender;
- (IBAction)cancelBtnPressed:(id _Nonnull)sender;
- (IBAction)retryAutoCaptureBtnPressed:(id _Nonnull)sender;
- (IBAction)onTapTakePhoto:(id _Nonnull)sender;
- (IBAction)torchSwitch:(id _Nonnull)sender;
- (IBAction)switchCameraBtnPressed:(id _Nonnull)sender;
- (void)updateDuration;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)cameraErrorMessageWithCamErrMsg:(NSString * _Nonnull)camErrMsg;
- (void)switchCamera;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class AVCapturePhotoOutput;
@class AVCapturePhoto;

@interface CameraVc2 (SWIFT_EXTENSION(ShuftiPro)) <AVCapturePhotoCaptureDelegate>
- (void)captureOutput:(AVCapturePhotoOutput * _Nonnull)output didFinishProcessingPhoto:(AVCapturePhoto * _Nonnull)photo error:(NSError * _Nullable)error;
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

@interface CameraVc2 (SWIFT_EXTENSION(ShuftiPro)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end



@class AVCaptureFileOutput;
@class NSURL;

@interface CameraVc2 (SWIFT_EXTENSION(ShuftiPro))
- (void)captureOutput:(AVCaptureFileOutput * _Nonnull)output didFinishRecordingToOutputFileAtURL:(NSURL * _Nonnull)outputFileURL fromConnections:(NSArray<AVCaptureConnection *> * _Nonnull)connections error:(NSError * _Nullable)error;
@end


@interface CameraVc2 (SWIFT_EXTENSION(ShuftiPro))
- (void)updateInstructionTimer;
@end

@class UIImage;

@interface CameraVc2 (SWIFT_EXTENSION(ShuftiPro))
- (void)image:(UIImage * _Nonnull)image didFinishSavingWithError:(NSError * _Nullable)error contextInfo:(void const * _Nonnull)contextInfo;
@end



/// An Objective-C compatible wrapper around Lottie’s Animation class.
/// Use in tandem with CompatibleAnimationView when using Lottie in Objective-C
SWIFT_CLASS("_TtC9ShuftiPro19CompatibleAnimation")
@interface CompatibleAnimation : NSObject
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name subdirectory:(NSString * _Nullable)subdirectory bundle:(NSBundle * _Nonnull)bundle OBJC_DESIGNATED_INITIALIZER;
+ (CompatibleAnimation * _Nonnull)named:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// An Objective-C compatible wrapper around Lottie’s AnimationKeypath
SWIFT_CLASS("_TtC9ShuftiPro26CompatibleAnimationKeypath")
@interface CompatibleAnimationKeypath : NSObject
/// Creates a keypath from a dot separated string. The string is separated by “.”
- (nonnull instancetype)initWithKeypath:(NSString * _Nonnull)keypath OBJC_DESIGNATED_INITIALIZER;
/// Creates a keypath from a list of strings.
- (nonnull instancetype)initWithKeys:(NSArray<NSString *> * _Nonnull)keys OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum CompatibleRenderingEngineOption : NSInteger;
@class NSData;
@class CompatibleDictionaryTextProvider;

/// An Objective-C compatible wrapper around Lottie’s LottieAnimationView.
SWIFT_CLASS("_TtC9ShuftiPro23CompatibleAnimationView")
@interface CompatibleAnimationView : UIView
/// Initializes a compatible AnimationView with a given compatible animation. Defaults to using
/// the rendering engine specified in LottieConfiguration.shared.
- (nonnull instancetype)initWithCompatibleAnimation:(CompatibleAnimation * _Nonnull)compatibleAnimation;
/// Initializes a compatible AnimationView with a given compatible animation and rendering engine
/// configuration.
- (nonnull instancetype)initWithCompatibleAnimation:(CompatibleAnimation * _Nonnull)compatibleAnimation compatibleRenderingEngineOption:(enum CompatibleRenderingEngineOption)compatibleRenderingEngineOption OBJC_DESIGNATED_INITIALIZER;
/// Initializes a compatible AnimationView with the resources asynchronously loaded from a given
/// URL. Defaults to using the rendering engine specified in LottieConfiguration.shared.
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url;
/// Initializes a compatible AnimationView with the resources asynchronously loaded from a given
/// URL using the given rendering engine configuration.
- (nonnull instancetype)initWithUrl:(NSURL * _Nonnull)url compatibleRenderingEngineOption:(enum CompatibleRenderingEngineOption)compatibleRenderingEngineOption OBJC_DESIGNATED_INITIALIZER;
/// Initializes a compatible AnimationView from a given Data object specifying the Lottie
/// animation. Defaults to using the rendering engine specified in LottieConfiguration.shared.
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data;
/// Initializes a compatible AnimationView from a given Data object specifying the Lottie
/// animation using the given rendering engine configuration.
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data compatibleRenderingEngineOption:(enum CompatibleRenderingEngineOption)compatibleRenderingEngineOption OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) CompatibleAnimation * _Nullable compatibleAnimation;
@property (nonatomic) CGFloat loopAnimationCount;
@property (nonatomic, strong) CompatibleDictionaryTextProvider * _Nullable compatibleDictionaryTextProvider;
@property (nonatomic) UIViewContentMode contentMode;
@property (nonatomic) BOOL shouldRasterizeWhenIdle;
@property (nonatomic) CGFloat currentProgress;
@property (nonatomic, readonly) CGFloat duration;
@property (nonatomic) NSTimeInterval currentTime;
@property (nonatomic) CGFloat currentFrame;
@property (nonatomic, readonly) CGFloat realtimeAnimationFrame;
@property (nonatomic, readonly) CGFloat realtimeAnimationProgress;
@property (nonatomic) CGFloat animationSpeed;
@property (nonatomic) BOOL respectAnimationFrameRate;
@property (nonatomic, readonly) BOOL isAnimationPlaying;
- (void)play;
- (void)playWithCompletion:(void (^ _Nullable)(BOOL))completion;
/// Note: When calling this code from Objective-C, the method signature is
/// playFromProgress:toProgress:completion which drops the standard “With” naming convention.
- (void)playFromProgress:(CGFloat)fromProgress toProgress:(CGFloat)toProgress completion:(void (^ _Nullable)(BOOL))completion;
/// Note: When calling this code from Objective-C, the method signature is
/// playFromFrame:toFrame:completion which drops the standard “With” naming convention.
- (void)playFromFrame:(CGFloat)fromFrame toFrame:(CGFloat)toFrame completion:(void (^ _Nullable)(BOOL))completion;
/// Note: When calling this code from Objective-C, the method signature is
/// playFromMarker:toMarker:completion which drops the standard “With” naming convention.
- (void)playFromMarker:(NSString * _Nonnull)fromMarker toMarker:(NSString * _Nonnull)toMarker completion:(void (^ _Nullable)(BOOL))completion;
- (void)playWithMarker:(NSString * _Nonnull)marker completion:(void (^ _Nullable)(BOOL))completion;
- (void)stop;
- (void)pause;
- (void)reloadImages;
- (void)forceDisplayUpdate;
- (id _Nullable)getValueFor:(CompatibleAnimationKeypath * _Nonnull)keypath atFrame:(CGFloat)atFrame SWIFT_WARN_UNUSED_RESULT;
- (void)logHierarchyKeypaths;
- (void)setColorValue:(UIColor * _Nonnull)color forKeypath:(CompatibleAnimationKeypath * _Nonnull)keypath;
- (UIColor * _Nullable)getColorValueFor:(CompatibleAnimationKeypath * _Nonnull)keypath atFrame:(CGFloat)atFrame SWIFT_WARN_UNUSED_RESULT;
- (void)addSubview:(AnimationSubview * _Nonnull)subview forLayerAt:(CompatibleAnimationKeypath * _Nonnull)keypath;
- (CGRect)convertWithRect:(CGRect)rect toLayerAt:(CompatibleAnimationKeypath * _Nullable)keypath SWIFT_WARN_UNUSED_RESULT;
- (CGPoint)convertWithPoint:(CGPoint)point toLayerAt:(CompatibleAnimationKeypath * _Nullable)keypath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)progressTimeForMarker:(NSString * _Nonnull)named SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)frameTimeForMarker:(NSString * _Nonnull)named SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)durationFrameTimeForMarker:(NSString * _Nonnull)named SWIFT_WARN_UNUSED_RESULT;
@end


/// An Objective-C compatible wrapper around Lottie’s DictionaryTextProvider.
/// Use in tandem with CompatibleAnimationView to supply text to LottieAnimationView
/// when using Lottie in Objective-C.
SWIFT_CLASS("_TtC9ShuftiPro32CompatibleDictionaryTextProvider")
@interface CompatibleDictionaryTextProvider : NSObject
- (nonnull instancetype)initWithValues:(NSDictionary<NSString *, NSString *> * _Nonnull)values OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// An Objective-C compatible wrapper around Lottie’s RenderingEngineOption enum. Pass in an option
/// to the CompatibleAnimationView initializers to configure the rendering engine for the view.
typedef SWIFT_ENUM(NSInteger, CompatibleRenderingEngineOption, open) {
/// Uses the rendering engine specified in LottieConfiguration.shared.
  CompatibleRenderingEngineOptionShared = 0,
/// Uses the library default rendering engine, coreAnimation.
  CompatibleRenderingEngineOptionDefaultEngine = 1,
/// Optimizes rendering performance by using the Core Animation rendering engine for animations it
/// can render while falling back to the main thread renderer for all other animations.
  CompatibleRenderingEngineOptionAutomatic = 2,
/// Only renders animations using the main thread rendering engine.
  CompatibleRenderingEngineOptionMainThread = 3,
/// Only renders animations using the Core Animation rendering engine. Those animations that use
/// features not yet supported on this renderer will not be rendered.
  CompatibleRenderingEngineOptionCoreAnimation = 4,
};


/// The base class for a child layer of CompositionContainer
SWIFT_CLASS("_TtC9ShuftiPro16CompositionLayer")
@interface CompositionLayer : CALayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class UIStackView;

SWIFT_CLASS("_TtC9ShuftiPro14ConfirmPhotoVc")
@interface ConfirmPhotoVc : UIViewController
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified faceImagePreview;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified confirmImageLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified previewPlayBtn;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playVideoView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified retakeBtn;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified yesContinueBtn;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified bottomButtonsStackView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified backBtnImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified loadingView;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified loadingIndicatorImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified documentLbl;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified retakeBtnView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified continueBtnView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified detectedDocumentTypeLbl;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (IBAction)backBtnPressed:(id _Nonnull)sender;
- (IBAction)previewPlayBtnPressed:(id _Nonnull)sender;
- (IBAction)retakeBtnPressed:(id _Nonnull)sender;
- (IBAction)yesContinueBtnPressed:(id _Nonnull)sender;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






/// The root <code>CALayer</code> of the Core Animation rendering engine
SWIFT_CLASS("_TtC9ShuftiPro18CoreAnimationLayer")
@interface CoreAnimationLayer : BaseAnimationLayer
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSublayers;
- (void)display;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@protocol CAAction;

/// A CALayer subclass that renders text content using CoreText
SWIFT_CLASS("_TtC9ShuftiPro19CoreTextRenderLayer")
@interface CoreTextRenderLayer : CALayer
- (id <CAAction> _Nullable)actionForKey:(NSString * _Nonnull)_ SWIFT_WARN_UNUSED_RESULT;
- (void)drawInContext:(CGContextRef _Nonnull)ctx;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UISearchBar;
@class UITableView;

SWIFT_CLASS("_TtC9ShuftiPro18CountrySelectionVc")
@interface CountrySelectionVc : UIViewController
@property (nonatomic, weak) IBOutlet UISearchBar * _Null_unspecified searchBar;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified supportedTypeSubHeading;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified countryUIView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLbl;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified backBtnImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabel;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (IBAction)backBtnPreesed:(id _Nonnull)sender;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CountrySelectionVc (SWIFT_EXTENSION(ShuftiPro)) <UISearchBarDelegate>
- (void)searchBarCancelButtonClicked:(UISearchBar * _Nonnull)searchBar;
- (void)searchBarTextDidEndEditing:(UISearchBar * _Nonnull)searchBar;
- (void)searchBar:(UISearchBar * _Nonnull)searchBar textDidChange:(NSString * _Nonnull)searchText;
@end

@class NSIndexPath;
@class UITableViewCell;

@interface CountrySelectionVc (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UIWindow;
@class UIApplication;

SWIFT_CLASS("_TtC9ShuftiPro17CustomAppDelegate")
@interface CustomAppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * _Nullable window;
- (UIInterfaceOrientationMask)application:(UIApplication * _Nonnull)application supportedInterfaceOrientationsForWindow:(UIWindow * _Nullable)window SWIFT_WARN_UNUSED_RESULT;
- (void)application:(UIApplication * _Nonnull)application handleEventsForBackgroundURLSession:(NSString * _Nonnull)handleEventsForBackgroundURLSessionidentifier completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)applicationDidEnterBackground:(UIApplication * _Nonnull)application;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro10DebugLayer")
@interface DebugLayer : CALayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer SWIFT_UNAVAILABLE;
@end

@class UITextView;
@class NSNotification;

SWIFT_CLASS("_TtC9ShuftiPro22DeclarationOfConsentVc")
@interface DeclarationOfConsentVc : UIViewController <UIGestureRecognizerDelegate, UITextViewDelegate>
@property (nonatomic, copy) IBOutletCollection(UILabel) NSArray<UILabel *> * _Null_unspecified instructionsTitle;
@property (nonatomic, copy) IBOutletCollection(UILabel) NSArray<UILabel *> * _Null_unspecified setLineSpaceLbl;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImageConsent;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabelConsent;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified proceedBtn;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified declarationOfConsentUIView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified agreeToPrivacyBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified continueBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cancelBtn;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified aggreeToPrivacyPolicyImageview;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified lblTermsAndConditions;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentTitleLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentHeadingLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentLowerHeadingLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentLbl;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)callBackWithNotification:(NSNotification * _Nonnull)notification;
- (IBAction)proceedBtnPressed:(id _Nonnull)sender;
- (IBAction)cancelInstructionBtnPressed:(id _Nonnull)sender;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)scrollViewWillBeginZooming:(UIScrollView * _Nonnull)scrollView withView:(UIView * _Nullable)view;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIGestureRecognizer;
@class UITapGestureRecognizer;

@interface DeclarationOfConsentVc (SWIFT_EXTENSION(ShuftiPro))
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldInteractWithURL:(NSURL * _Nonnull)URL inRange:(NSRange)characterRange interaction:(UITextItemInteraction)interaction SWIFT_WARN_UNUSED_RESULT;
- (void)tapTextViewWithSender:(UITapGestureRecognizer * _Nonnull)sender;
- (IBAction)continueBtnPressed:(id _Nonnull)sender;
- (IBAction)cancelBtnPressed:(id _Nonnull)sender;
- (IBAction)agreeToPrivacyPressed:(id _Nonnull)sender;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC9ShuftiPro14DesignableView")
@interface DesignableView : UIView
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColor;
@property (nonatomic) IBInspectable CGFloat borderWidth;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class NSStream;

SWIFT_CLASS("_TtC9ShuftiPro19FoundationTransport")
@interface FoundationTransport : NSObject <NSStreamDelegate>
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A <code>CAGradientLayer</code> subclass used to render a gradient <em>outside</em> the normal layer bounds
/// <ul>
///   <li>
///     <code>GradientFill.startPoint</code> and <code>GradientFill.endPoint</code> are expressed
///     with respect to the <code>bounds</code> of the <code>ShapeItemLayer</code>.
///   </li>
///   <li>
///     The gradient itself is supposed to be rendered infinitely in all directions
///     (e.g. including outside of <code>bounds</code>). This is because <code>ShapeItemLayer</code> paths
///     don’t necessarily sit within the layer’s <code>bounds</code>.
///   </li>
///   <li>
///     To support this, <code>GradientRenderLayer</code> tracks a <code>gradientReferenceBounds</code>
///     that <code>startPoint</code> / <code>endPoint</code> are calculated relative to.
///     The <em>actual</em> <code>bounds</code> of this layer is padded by a large amount so that
///     the gradient can be drawn outside of the <code>gradientReferenceBounds</code>.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC9ShuftiPro19GradientRenderLayer")
@interface GradientRenderLayer : CAGradientLayer
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




/// The CALayer type responsible for rendering <code>Group</code>s
SWIFT_CLASS("_TtC9ShuftiPro10GroupLayer")
@interface GroupLayer : BaseAnimationLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ShuftiPro21ImageCompositionLayer")
@interface ImageCompositionLayer : CompositionLayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@end


/// The <code>CALayer</code> type responsible for rendering <code>ImageLayerModel</code>s
SWIFT_CLASS("_TtC9ShuftiPro10ImageLayer")
@interface ImageLayer : BaseCompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end



/// A <code>BaseAnimationLayer</code> subclass that renders its background color
/// as if the layer is infinitely large, without affecting its bounds
/// or the bounds of its sublayers
SWIFT_CLASS("_TtC9ShuftiPro28InfiniteOpaqueAnimationLayer")
@interface InfiniteOpaqueAnimationLayer : BaseAnimationLayer
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSublayers;
@end


SWIFT_CLASS("_TtC9ShuftiPro13InstructionVc")
@interface InstructionVc : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified documentInstructions;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified faceInstructions;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionsTitle;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified addressInstructionsView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified consentInstructions;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified crossBtnImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel3;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel4;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified docLabel5;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified addressLbl1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified addressLbl2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified addressLbl3;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentLbl1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentLbl2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified consentLbl3;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified faceLabel1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified faceLabel2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified faceLabel3;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified mainInstructionView;
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified instructionsScrollView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified instructionsSubView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified InstructionImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified InstructionsHeading;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionsText1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionsText2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionsText3;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)instructionNotificationWithNotification:(NSNotification * _Nonnull)notification;
- (IBAction)dismissBtn:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A layer that inverses the alpha output of its input layer.
/// WARNING: This is experimental and probably not very performant.
SWIFT_CLASS("_TtC9ShuftiPro18InvertedMatteLayer")
@interface InvertedMatteLayer : CALayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (void)drawInContext:(CGContextRef _Nonnull)ctx;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ShuftiPro13LoadingButton")
@interface LoadingButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro18LocalizationSystem")
@interface LocalizationSystem : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// The base view for <code>LottieAnimationView</code> on iOS, tvOS, watchOS, and macCatalyst.
/// Enables the <code>LottieAnimationView</code> implementation to be shared across platforms.
SWIFT_CLASS("_TtC9ShuftiPro23LottieAnimationViewBase")
@interface LottieAnimationViewBase : UIView
@property (nonatomic) UIViewContentMode contentMode;
- (void)didMoveToWindow;
- (void)layoutSubviews;
- (void)animationWillMoveToBackground;
- (void)animationWillEnterForeground;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC9ShuftiPro19LottieAnimationView")
@interface LottieAnimationView : LottieAnimationViewBase
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
/// Set animation name from Interface Builder
@property (nonatomic, copy) IBInspectable NSString * _Nullable animationName;
- (void)animationWillMoveToBackground;
- (void)animationWillEnterForeground;
@end




/// The base <code>CALayer</code> for the Main Thread rendering engine
/// This layer holds a single composition container and allows for animation of
/// the currentFrame property.
SWIFT_CLASS("_TtC9ShuftiPro24MainThreadAnimationLayer")
@interface MainThreadAnimationLayer : CALayer
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
+ (BOOL)needsDisplayForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (id <CAAction> _Nullable)actionForKey:(NSString * _Nonnull)event SWIFT_WARN_UNUSED_RESULT;
- (void)display;
/// The animatable Current Frame Property
@property (nonatomic) CGFloat currentFrame;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// The CALayer type responsible for rendering the <code>Mask</code> of a <code>BaseCompositionLayer</code>
SWIFT_CLASS("_TtC9ShuftiPro20MaskCompositionLayer")
@interface MaskCompositionLayer : CALayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSublayers;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface MaskCompositionLayer (SWIFT_EXTENSION(ShuftiPro))
@end



SWIFT_CLASS("_TtC9ShuftiPro18MaskContainerLayer")
@interface MaskContainerLayer : CALayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC9ShuftiPro7NFCCell")
@interface NFCCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified tileLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nfcDetailLbl;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro18NFCDetailTableCell")
@interface NFCDetailTableCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nfcDetailHeading;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nfcDetailSubText;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified sepratorView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro17NFCImageTableCell")
@interface NFCImageTableCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified nfcPhoto;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end







@class NSURLSession;
@class NSURLSessionWebSocketTask;

SWIFT_CLASS("_TtC9ShuftiPro12NativeEngine") SWIFT_AVAILABILITY(tvos,introduced=13.0) SWIFT_AVAILABILITY(watchos,introduced=6.0) SWIFT_AVAILABILITY(ios,introduced=13.0) SWIFT_AVAILABILITY(macos,introduced=10.15)
@interface NativeEngine : NSObject <NSURLSessionDataDelegate, NSURLSessionWebSocketDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session webSocketTask:(NSURLSessionWebSocketTask * _Nonnull)webSocketTask didOpenWithProtocol:(NSString * _Nullable)protocol;
- (void)URLSession:(NSURLSession * _Nonnull)session webSocketTask:(NSURLSessionWebSocketTask * _Nonnull)webSocketTask didCloseWithCode:(NSURLSessionWebSocketCloseCode)closeCode reason:(NSData * _Nullable)reason;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro20NullCompositionLayer")
@interface NullCompositionLayer : CompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end



/// A class that represents an emit that will request an ack that has not yet been sent.
/// Call <code>timingOut(after:callback:)</code> to complete the emit
/// Example:
/// \code
/// socket.emitWithAck("myEvent").timingOut(after: 1) {data in
///     ...
/// }
///
/// \endcode
SWIFT_CLASS("_TtC9ShuftiPro13OnAckCallback")
@interface OnAckCallback : NSObject
/// Completes an emitWithAck. If this isn’t called, the emit never happens.
/// \param seconds The number of seconds before this emit times out if an ack hasn’t been received.
///
/// \param callback The callback called when an ack is received, or when a timeout happens.
/// To check for timeout, use <code>SocketAckStatus</code>’s <code>noAck</code> case.
///
- (void)timingOutAfter:(double)seconds callback:(void (^ _Nonnull)(NSArray * _Nonnull))callback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The <code>CALayer</code> type responsible for rendering <code>PreCompLayerModel</code>s
SWIFT_CLASS("_TtC9ShuftiPro12PreCompLayer")
@interface PreCompLayer : BaseCompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC9ShuftiPro19PreCompositionLayer")
@interface PreCompositionLayer : CompositionLayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@end

@class UIActivityIndicatorView;
@class WKNavigation;

SWIFT_CLASS("_TtC9ShuftiPro22PrivacyPolicyWebviewVc")
@interface PrivacyPolicyWebviewVc : UIViewController <UIScrollViewDelegate, UIWebViewDelegate, WKNavigationDelegate, WKUIDelegate>
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activity;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified privacyPolicyView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cancelBtn;
- (void)viewDidLoad;
- (IBAction)cancelWebViewBtnWithSender:(id _Null_unspecified)sender;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC9ShuftiPro14RAProgressRing")
@interface RAProgressRing : UIView
@property (nonatomic) IBInspectable CGFloat lineWidth;
@property (nonatomic) IBInspectable CGFloat animationDuration;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull trackColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull circleColor;
@property (nonatomic) IBInspectable CGFloat progress;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// A layer that renders a child layer at some offset using a <code>Repeater</code>
SWIFT_CLASS("_TtC9ShuftiPro13RepeaterLayer")
@interface RepeaterLayer : BaseAnimationLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ShuftiPro8ResultVc")
@interface ResultVc : UIViewController <NSURLSessionTaskDelegate, MFMailComposeViewControllerDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified loadingView;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified loadingIndicatorImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified waitingMessageLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified resultsView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified verifiedLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified verifiedDescLbl;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified verifiedImageWebView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified lblTermsAndConditions;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleOnLoadingLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified pleaseWaitLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified uploadPercentageLbl;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified proceedBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified retrySendRequestBtn;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImageOnLoading;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabelOnLoading;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)retrySendRequestBtnPressed:(id _Nonnull)sender;
- (IBAction)resultsProceedBtnPressed:(id _Nonnull)sender;
- (void)updateScreenOnInternetError;
- (void)checkRequestStatusApi;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ResultVc (SWIFT_EXTENSION(ShuftiPro)) <NSURLSessionDelegate>
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(NSURLSession * _Nonnull)session;
@end


@class MFMailComposeViewController;

@interface ResultVc (SWIFT_EXTENSION(ShuftiPro))
- (void)tappedOnLabel:(UITapGestureRecognizer * _Nonnull)gesture;
- (void)mailComposeController:(MFMailComposeViewController * _Nonnull)controller didFinishWithResult:(MFMailComposeResult)result error:(NSError * _Nullable)error;
@end

@class NSURLSessionTask;
@class NSURLSessionDownloadTask;

@interface ResultVc (SWIFT_EXTENSION(ShuftiPro)) <NSURLSessionDownloadDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didFinishDownloadingToURL:(NSURL * _Nonnull)location;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
@end


/// A CompositionLayer responsible for initializing and rendering shapes
SWIFT_CLASS("_TtC9ShuftiPro21ShapeCompositionLayer")
@interface ShapeCompositionLayer : CompositionLayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@end



/// The base layer that holds Shapes and Shape Renderers
SWIFT_CLASS("_TtC9ShuftiPro19ShapeContainerLayer")
@interface ShapeContainerLayer : CALayer
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end


/// A CALayer type that renders an array of <code>[ShapeItem]</code>s,
/// from a <code>Group</code> in a <code>ShapeLayerModel</code>.
SWIFT_CLASS("_TtC9ShuftiPro14ShapeItemLayer")
@interface ShapeItemLayer : BaseAnimationLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The CALayer type responsible for rendering <code>ShapeLayerModel</code>s
SWIFT_CLASS("_TtC9ShuftiPro10ShapeLayer")
@interface ShapeLayer : BaseCompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end


/// The layer responsible for rendering shape objects
SWIFT_CLASS("_TtC9ShuftiPro16ShapeRenderLayer")
@interface ShapeRenderLayer : ShapeContainerLayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (void)drawInContext:(CGContextRef _Nonnull)ctx;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC9ShuftiPro9ShuftiPro")
@interface ShuftiPro : NSObject
- (NSString * _Nonnull)getUniqueReference SWIFT_WARN_UNUSED_RESULT;
- (void)shuftiProVerificationWithRequestObject:(NSDictionary<NSString *, id> * _Nonnull)dataObjectObj authKeys:(NSDictionary<NSString *, NSString *> * _Nonnull)authKeys parentVC:(UIViewController * _Nonnull)pvc configs:(NSDictionary<NSString *, id> * _Nullable)configs completion:(void (^ _Nonnull)(id _Nonnull))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class SocketRawAckView;

/// A class that represents a waiting ack call.
/// <em>NOTE</em>: You should not store this beyond the life of the event handler.
SWIFT_CLASS("_TtC9ShuftiPro16SocketAckEmitter")
@interface SocketAckEmitter : NSObject
/// A view into this emitter where emits do not check for binary data.
/// Usage:
/// \code
/// ack.rawEmitView.with(myObject)
///
/// \endcode<em>NOTE</em>: It is not safe to hold on to this view beyond the life of the socket.
@property (nonatomic, readonly, strong) SocketRawAckView * _Nonnull rawEmitView;
/// Call to ack receiving this event.
/// \param items An array of items to send when acking. Use <code>[]</code> to send nothing.
///
- (void)with:(NSArray * _Nonnull)items;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents some event that was received.
SWIFT_CLASS("_TtC9ShuftiPro14SocketAnyEvent")
@interface SocketAnyEvent : NSObject
/// The event name.
@property (nonatomic, readonly, copy) NSString * _Nonnull event;
/// The data items for this event.
@property (nonatomic, readonly, copy) NSArray * _Nullable items;
/// The description of this event.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The class that handles the engine.io protocol and transports.
/// See <code>SocketEnginePollable</code> and <code>SocketEngineWebsocket</code> for transport specific methods.
SWIFT_CLASS("_TtC9ShuftiPro12SocketEngine")
@interface SocketEngine : NSObject <NSURLSessionDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




/// Declares that a type will be a delegate to an engine.
SWIFT_PROTOCOL("_TtP9ShuftiPro18SocketEngineClient_")
@protocol SocketEngineClient
/// Called when the engine errors.
/// \param reason The reason the engine errored.
///
- (void)engineDidErrorWithReason:(NSString * _Nonnull)reason;
/// Called when the engine closes.
/// \param reason The reason that the engine closed.
///
- (void)engineDidCloseWithReason:(NSString * _Nonnull)reason;
/// Called when the engine opens.
/// \param reason The reason the engine opened.
///
- (void)engineDidOpenWithReason:(NSString * _Nonnull)reason;
/// Called when the engine receives a ping message. Only called in socket.io >3.
- (void)engineDidReceivePing;
/// Called when the engine receives a pong message. Only called in socket.io 2.
- (void)engineDidReceivePong;
/// Called when the engine sends a ping to the server. Only called in socket.io 2.
- (void)engineDidSendPing;
/// Called when the engine sends a pong to the server. Only called in socket.io >3.
- (void)engineDidSendPong;
/// Called when the engine has a message that must be parsed.
/// \param msg The message that needs parsing.
///
- (void)parseEngineMessage:(NSString * _Nonnull)msg;
/// Called when the engine receives binary data.
/// \param data The data the engine received.
///
- (void)parseEngineBinaryData:(NSData * _Nonnull)data;
/// Called when when upgrading the http connection to a websocket connection.
/// \param headers The http headers.
///
- (void)engineDidWebsocketUpgradeWithHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)headers;
@end

/// Represents the type of engine.io packet types.
typedef SWIFT_ENUM(NSInteger, SocketEnginePacketType, open) {
/// Open message.
  SocketEnginePacketTypeOpen = 0,
/// Close message.
  SocketEnginePacketTypeClose = 1,
/// Ping message.
  SocketEnginePacketTypePing = 2,
/// Pong message.
  SocketEnginePacketTypePong = 3,
/// Regular message.
  SocketEnginePacketTypeMessage = 4,
/// Upgrade message.
  SocketEnginePacketTypeUpgrade = 5,
/// NOOP.
  SocketEnginePacketTypeNoop = 6,
};


/// Represents a socket.io-client.
/// Clients are created through a <code>SocketManager</code>, which owns the <code>SocketEngineSpec</code> that controls the connection to the server.
/// For example:
/// \code
/// // Create a socket for the /swift namespace
/// let socket = manager.socket(forNamespace: "/swift")
///
/// // Add some handlers and connect
///
/// \endcode<em>NOTE</em>: The client is not thread/queue safe, all interaction with the socket should be done on the <code>manager.handleQueue</code>
SWIFT_CLASS("_TtC9ShuftiPro14SocketIOClient")
@interface SocketIOClient : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents state of a manager or client.
typedef SWIFT_ENUM(NSInteger, SocketIOStatus, open) {
/// The client/manager has never been connected. Or the client has been reset.
  SocketIOStatusNotConnected = 0,
/// The client/manager was once connected, but not anymore.
  SocketIOStatusDisconnected = 1,
/// The client/manager is in the process of connecting.
  SocketIOStatusConnecting = 2,
/// The client/manager is currently connected.
  SocketIOStatusConnected = 3,
};


/// A manager for a socket.io connection.
/// A <code>SocketManager</code> is responsible for multiplexing multiple namespaces through a single <code>SocketEngineSpec</code>.
/// Example:
/// \code
/// let manager = SocketManager(socketURL: URL(string:"http://localhost:8080/")!)
/// let defaultNamespaceSocket = manager.defaultSocket
/// let swiftSocket = manager.socket(forNamespace: "/swift")
///
/// // defaultNamespaceSocket and swiftSocket both share a single connection to the server
///
/// \endcodeSockets created through the manager are retained by the manager. So at the very least, a single strong reference
/// to the manager must be maintained to keep sockets alive.
/// To disconnect a socket and remove it from the manager, either call <code>SocketIOClient.disconnect()</code> on the socket,
/// or call one of the <code>disconnectSocket</code> methods on this class.
/// <em>NOTE</em>: The manager is not thread/queue safe, all interaction with the manager should be done on the <code>handleQueue</code>
SWIFT_CLASS("_TtC9ShuftiPro13SocketManager")
@interface SocketManager : NSObject
/// Not so type safe way to create a SocketIOClient, meant for Objective-C compatiblity.
/// If using Swift it’s recommended to use <code>init(socketURL: NSURL, options: Set<SocketIOClientOption>)</code>
/// \param socketURL The url of the socket.io server.
///
/// \param config The config for this socket.
///
- (nonnull instancetype)initWithSocketURL:(NSURL * _Nonnull)socketURL config:(NSDictionary<NSString *, id> * _Nullable)config;
/// Called when the engine closes.
/// \param reason The reason that the engine closed.
///
- (void)engineDidCloseWithReason:(NSString * _Nonnull)reason;
/// Called when the engine errors.
/// \param reason The reason the engine errored.
///
- (void)engineDidErrorWithReason:(NSString * _Nonnull)reason;
/// Called when the engine opens.
/// \param reason The reason the engine opened.
///
- (void)engineDidOpenWithReason:(NSString * _Nonnull)reason;
/// Called when the engine receives a ping message.
- (void)engineDidReceivePing;
/// Called when the sends a ping to the server.
- (void)engineDidSendPing;
/// Called when the engine receives a pong message.
- (void)engineDidReceivePong;
/// Called when the sends a pong to the server.
- (void)engineDidSendPong;
/// Called when when upgrading the http connection to a websocket connection.
/// \param headers The http headers.
///
- (void)engineDidWebsocketUpgradeWithHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)headers;
/// Called when the engine has a message that must be parsed.
/// \param msg The message that needs parsing.
///
- (void)parseEngineMessage:(NSString * _Nonnull)msg;
/// Called when the engine receives binary data.
/// \param data The data the engine received.
///
- (void)parseEngineBinaryData:(NSData * _Nonnull)data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Class that gives a backwards compatible way to cause an emit not to recursively check for Data objects.
/// Usage:
/// \code
/// ack.rawEmitView.with(myObject)
///
/// \endcode
SWIFT_CLASS("_TtC9ShuftiPro16SocketRawAckView")
@interface SocketRawAckView : NSObject
/// Call to ack receiving this event.
/// \param items An array of items to send when acking. Use <code>[]</code> to send nothing.
///
- (void)with:(NSArray * _Nonnull)items;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Class that gives a backwards compatible way to cause an emit not to recursively check for Data objects.
/// Usage:
/// \code
/// socket.rawEmitView.emit("myEvent", myObject)
///
/// \endcode
SWIFT_CLASS("_TtC9ShuftiPro13SocketRawView")
@interface SocketRawView : NSObject
/// Same as emit, but meant for Objective-C
/// \param event The event to send.
///
/// \param items The items to send with this event. Send an empty array to send no data.
///
- (void)emit:(NSString * _Nonnull)event with:(NSArray * _Nonnull)items;
/// Same as emitWithAck, but for Objective-C
/// <em>NOTE</em>: It is up to the server send an ack back, just calling this method does not mean the server will ack.
/// Check that your server’s api will ack the event being sent.
/// Example:
/// \code
/// socket.emitWithAck("myEvent", with: [1]).timingOut(after: 1) {data in
///     ...
/// }
///
/// \endcode\param event The event to send.
///
/// \param items The items to send with this event. Use <code>[]</code> to send nothing.
///
///
/// returns:
/// An <code>OnAckCallback</code>. You must call the <code>timingOut(after:)</code> method before the event will be sent.
- (OnAckCallback * _Nonnull)emitWithAck:(NSString * _Nonnull)event with:(NSArray * _Nonnull)items SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC9ShuftiPro21SolidCompositionLayer")
@interface SolidCompositionLayer : CompositionLayer
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro10SolidLayer")
@interface SolidLayer : BaseCompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro11StepperView")
@interface StepperView : UIView
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified currentServiceLbl;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified faceView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified docView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified doc2View;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified addressView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified consentView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified parentView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro18SupportedTypesCell")
@interface SupportedTypesCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified supportedTypes;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified supportedTypesImage;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified proceedImg;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified proceedView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified leftBorderView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified rightBorderView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified topBorderView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified bottomBorderView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSLayoutConstraint;

SWIFT_CLASS("_TtC9ShuftiPro16SupportedTypesVc")
@interface SupportedTypesVc : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLbl;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified supportedTypesUIView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified countryView;
@property (nonatomic, strong) IBOutlet UITableView * _Null_unspecified supportedTypesTableview;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified supportedTypeSubHeading;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified backBtnImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified countryDropdownImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified selectedCountryLabel;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified supportedDocLabel;
@property (nonatomic, strong) IBOutlet UIButton * _Null_unspecified selectedCountryBtn;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified tableViewHeight;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified supportedDocLabelTopConstraint;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (IBAction)backBtnPreesed:(id _Nonnull)sender;
- (IBAction)countrySelectionBtnPreesed:(id _Nonnull)sender;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@interface SupportedTypesVc (SWIFT_EXTENSION(ShuftiPro)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC9ShuftiPro11TestIDsCell")
@interface TestIDsCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified imageView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_CLASS("_TtC9ShuftiPro9TestIDsVc")
@interface TestIDsVc : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified container;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified transparentView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified containerHight;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)dismissContainerGestureWithTapGestureRecognizer:(UITapGestureRecognizer * _Nonnull)tapGestureRecognizer;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewLayout;

@interface TestIDsVc (SWIFT_EXTENSION(ShuftiPro)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface TestIDsVc (SWIFT_EXTENSION(ShuftiPro)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC9ShuftiPro20TextCompositionLayer")
@interface TextCompositionLayer : CompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end


/// The <code>CALayer</code> type responsible for rendering <code>TextLayer</code>s
SWIFT_CLASS("_TtC9ShuftiPro9TextLayer")
@interface TextLayer : BaseCompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ OBJC_DESIGNATED_INITIALIZER;
/// Called by CoreAnimation to create a shadow copy of this layer
/// More details: https://developer.apple.com/documentation/quartzcore/calayer/1410842-init
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end


/// The CALayer type responsible for only rendering the <code>transform</code> of a <code>LayerModel</code>
SWIFT_CLASS("_TtC9ShuftiPro14TransformLayer")
@interface TransformLayer : BaseCompositionLayer
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)argument OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithLayer:(id _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
@end

















SWIFT_CLASS("_TtC9ShuftiPro19UploadOrTakePhotoVc")
@interface UploadOrTakePhotoVc : UIViewController
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified cameraImg;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified uploadImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified cameraProceedImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified uploadProceedImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified recordImg;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified takePhotoLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified bottomHeadingLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified uploadPhotoLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified recordVideoLbl;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cameraView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified uploadView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified recordView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cameraProceedView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified uploadProceedView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified videoProceedView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified bckBtnImage;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified videoImg;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabel;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (IBAction)takePhotoBtnPressed:(id _Nonnull)sender;
- (IBAction)uploadFromGalleryBtnPressed:(id _Nonnull)sender;
- (IBAction)recordVideoBtnPressed:(id _Nonnull)sender;
- (IBAction)backBtnPressed:(id _Nonnull)sender;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9ShuftiPro13UploadVideoVc")
@interface UploadVideoVc : UIViewController <UIDocumentPickerDelegate>
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified imagePreview;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified animationImagePreview;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified powerdByLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionsLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionsLbl1;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified instructionsLbl2;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified confirmImageLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified retakeBtn;
@property (nonatomic, weak) IBOutlet LoadingButton * _Null_unspecified yesContinueBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified uploadBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified previewPlayBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified testIDsBtn;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified backBtnImg;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified playVideoView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified retakeStackViewBtns;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImage;
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified uploadTypeImg;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified bottomButtonsStackView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified verficationTypeLbl;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified loadingView;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified loaderWebView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)uploadVideoBtnPressed:(id _Nonnull)sender;
- (IBAction)retakeBtnPressed:(id _Nonnull)sender;
- (IBAction)continueBtnPressed:(id _Nonnull)sender;
- (IBAction)playVideoBtnPressed:(id _Nonnull)sender;
- (IBAction)backBtnPressed:(id _Nonnull)sender;
- (IBAction)testIDsBtnPressed:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



@class UIImagePickerController;

@interface UploadVideoVc (SWIFT_EXTENSION(ShuftiPro)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
@end


@class UIDocumentPickerViewController;

@interface UploadVideoVc (SWIFT_EXTENSION(ShuftiPro))
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
- (void)documentPickerWasCancelled:(UIDocumentPickerViewController * _Nonnull)controller;
@end


@interface UploadVideoVc (SWIFT_EXTENSION(ShuftiPro))
- (void)imageTappedWithTapGestureRecognizer:(UITapGestureRecognizer * _Nonnull)tapGestureRecognizer;
- (void)handleGestureWithGesture:(UISwipeGestureRecognizer * _Nonnull)gesture;
@end



@class UINavigationBar;
@class UIBarButtonItem;
@class WKWebViewConfiguration;
@class WKNavigationAction;
@class WKWindowFeatures;

SWIFT_CLASS("_TtC9ShuftiPro17WebViewController")
@interface WebViewController : UIViewController <WKNavigationDelegate, WKUIDelegate>
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified pleaseWaitLbl;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified loadingView;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activity;
@property (nonatomic, weak) IBOutlet WKWebView * _Null_unspecified loadingIndicatorWebView;
@property (nonatomic, weak) IBOutlet UINavigationBar * _Null_unspecified navBar;
@property (nonatomic, weak) IBOutlet UIBarButtonItem * _Null_unspecified navBarCancelBtn;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified footerImage;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified footerLabel;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (void)callBackWithNotification:(NSNotification * _Nonnull)notification;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (WKWebView * _Nullable)webView:(WKWebView * _Nonnull)webView createWebViewWithConfiguration:(WKWebViewConfiguration * _Nonnull)configuration forNavigationAction:(WKNavigationAction * _Nonnull)navigationAction windowFeatures:(WKWindowFeatures * _Nonnull)windowFeatures SWIFT_WARN_UNUSED_RESULT;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (IBAction)navBarCancelBtnPressed:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface WebViewController (SWIFT_EXTENSION(ShuftiPro))
/// When a navigation action occurs for a link to wikipedia, ensure it gets
/// Moved out to the default browser.
- (void)webView:(WKWebView * _Nonnull)_ decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)decidePolicyFor decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
